"""Add dedup config

Revision ID: f4bf9d520087
Revises: c3d4e5f6g7h8
Create Date: 2026-08-07 05:38:51.085701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# revision identifiers, used by Alembic.
revision: str = 'f4bf9d520087'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedup_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('match_strategy', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedup_config_id'), 'dedup_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dedup_config_id'), table_name='dedup_config')
    op.drop_table('dedup_config')
    # ### end Alembic commands ###
